### ISSUE TITLE
what am I missing ?

### ISSUE THREAD

**Issue by Mokaaaaa** [crack00r/BitBot#5]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\BitBot-master\main.py", line 8, in <module>
    import Cryptoping, HandlerThread, BittrexThread, PoloniexThread
  File "C:\Users\User\Desktop\BitBot-master\Cryptoping.py", line 1, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

**Comment by Mokaaaaa** [comment]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\BitBot-master\main.py", line 21, in <module>
    cryptoping = Cryptoping.Cryptoping()
  File "C:\Users\user\Desktop\BitBot-master\Cryptoping.py", line 17, in __init__
    self.user = self.config.get('cryptoping', 'user')
  File "c:\Python27\lib\ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'cryptoping'
